apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace
  - namespace/namespace.yaml

  # Configuration
  - config/configmap-app.yaml
  - config/postgresql-secret.yaml
  - config/redis-secret.yaml

  # Application Services
  - services/catalog/deployment.yaml
  - services/catalog/service.yaml

  - services/identity/deployment.yaml
  - services/identity/service.yaml

  - services/cart/deployment.yaml
  - services/cart/service.yaml

  - services/inventory/deployment.yaml
  - services/inventory/service.yaml

  - services/order/deployment.yaml
  - services/order/service.yaml

  - services/payment/deployment.yaml
  - services/payment/service.yaml

  - services/notification/deployment.yaml
  - services/notification/service.yaml

  - services/gateway/deployment.yaml
  - services/gateway/service.yaml

  - services/frontend/deployment.yaml
  - services/frontend/service.yaml

  # Ingress
  - ingress/ingress.yaml

  # Network Policies


  # Autoscaling
  - autoscaling/01-gateway-hpa.yaml
  - autoscaling/02-catalog-hpa.yaml
  - autoscaling/03-identity-hpa.yaml
  - autoscaling/04-cart-hpa.yaml
  - autoscaling/05-inventory-hpa.yaml
  - autoscaling/06-order-hpa.yaml
  - autoscaling/07-payment-hpa.yaml
  - autoscaling/08-frontend-hpa.yaml