apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.storeName | default "global-vault" }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion | default "us-east-1" }}