apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-secret-sync
  namespace: cloudcart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudcart/prod/db-secrets