name: Terraform CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read

jobs:
  terraform-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Assume the AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: github-actions-terraform-ci
          audience: sts.amazonaws.com
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        working-directory: ./terraform
        run: terraform fmt -check -recursive

# CORE INFRASTRUCTURE
      - name: Terraform generate terraform.tfvars
        id: tfvars_core
        working-directory: ./terraform/core-infra
        run: |
          cp terraform.tfvars.example terraform.tfvars

      - name: Terraform Init
        id: init_core
        working-directory: ./terraform/core-infra
        run: terraform init -input=false -backend-config=core-infra-backend.conf
      
      - name: Terraform Validate
        id: validate_core
        working-directory: ./terraform/core-infra
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan_core
        working-directory: ./terraform/core-infra
        run: terraform plan -input=false -out=core-infra.tfplan -var-file=terraform.tfvars

# ENVIRONMENTS - DEV

      - name: Terraform Init
        id: init_dev
        working-directory: ./terraform/environments/dev
        run: terraform init -input=false -backend-config=dev-backend.conf
      
      - name: Terraform Validate
        id: validate_dev
        working-directory: ./terraform/environments/dev
        run: terraform validate -no-color

# ENVIRONMENTS - PROD

      - name: Terraform Init
        id: init_prod
        working-directory: ./terraform/environments/prod
        run: terraform init -input=false -backend-config=prod-backend.conf
      
      - name: Terraform Validate
        id: validate_prod
        working-directory: ./terraform/environments/prod
        run: terraform validate -no-color